platform :ios, ‘8.0’
use_frameworks!
target “CDYT_HoiDap” do

pod 'Alamofire', '~> 4.0’
pod 'RealmSwift'
pod 'SDWebImage'
pod 'SKPhotoBrowser', :git => 'https://github.com/suzuki-0000/SKPhotoBrowser.git', :branch => 'swift3'
pod 'DKImagePickerController'
pod 'ALTextInputBar'
pod 'TTTAttributedLabel'
pod 'UICollectionViewLeftAlignedLayout'
pod 'NVActivityIndicatorView'
pod 'UITextView+Placeholder'
pod 'ICSPullToRefresh'
pod 'WYPopoverController'
pod 'SendBirdSDK'
pod 'AlamofireImage'
pod 'MGSwipeTableCell'
pod 'Google/Analytics'
pod 'RNNotificationView'
pod 'FSCalendar'
pod 'PhoneNumberKit'
end
